import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <QueryClientProvider client={queryClient}>
      <html lang='en'>
        <body>{children}</body>
      </html>
    </QueryClientProvider>
  )
}
